import Header from './Header.js';
import Form from './Form.js';
import TabsCollection from './Tabs.js';
import Carousel from './Carousel.js';
import Subscribe from './Subscribe.js';
import GoToTop from './GoToTop.js';
import SearchCard from './SearchCard.js';
import LoadCards from './LoadCards.js';
import Countdown from './Countdown.js';
import DiscountSubscride from './DiscountSubscride.js';

const form = new Form();
new Header(form);
const loadCardsInstance = new LoadCards();
new TabsCollection(loadCardsInstance);
new Carousel();
new Subscribe();
new GoToTop();
new SearchCard(loadCardsInstance);
new Countdown();
new DiscountSubscride();