import Header from './Header.js';
import LogInForm from './LogInForm.js';
import TabsCollection from './Tabs.js';
import Carousel from './Carousel.js';
import Subscribe from './Subscribe.js';
import GoToTop from './GoToTop.js';
import SearchCard from './SearchCard.js';
import LoadCards from './LoadCards.js';
import Countdown from './Countdown.js';
import JoinForm from './JoinForm.js';
import InputMaskCollection from './InputMask.js';
import VideoPlayerCollection from './VideoPlayer.js';
import SelectCollection from './Select.js';
import SpinbuttonCollection from './Spinbutton.js';
import SwitchingListStyleCollection from './switchingListStyle.js';

const form = new LogInForm();
new Header(form);
const loadCardsInstance = new LoadCards();
new TabsCollection(loadCardsInstance);
new Carousel();
new Subscribe();
new GoToTop();
new SearchCard(loadCardsInstance);
new Countdown();
new JoinForm();
new InputMaskCollection();
new VideoPlayerCollection();
new SelectCollection();
new SpinbuttonCollection();
new SwitchingListStyleCollection();